### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by fiorin7** [IohannesArnold/lewis-short-json#1]
Hello, I didn't see the license of the data written anywhere. Is it available for non-commercial use?

**Comment by IohannesArnold** [comment]
These files are a transformation of what's available at https://github.com/PerseusDL/lexica, which are under Creative Commons Attribution-ShareAlike 3.0. Though, I would recommend against using what I've got in this repo, this was a hacky attempt at something that I didn't really finish. There are still errors in what I've done.

**Comment by fiorin7** [comment]
Thanks!
